[2023-06-09 13:51:52,148] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_dag.dbt-1 manual__2023-06-09T13:51:50.948754+00:00 [queued]>
[2023-06-09 13:51:52,154] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: my_dag.dbt-1 manual__2023-06-09T13:51:50.948754+00:00 [queued]>
[2023-06-09 13:51:52,154] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 13:51:52,154] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2023-06-09 13:51:52,154] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2023-06-09 13:51:52,166] {taskinstance.py:1264} INFO - Executing <Task(BashOperator): dbt-1> on 2023-06-09 13:51:50.948754+00:00
[2023-06-09 13:51:52,169] {standard_task_runner.py:52} INFO - Started process 6105 to run task
[2023-06-09 13:51:52,171] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'dbt-1', 'manual__2023-06-09T13:51:50.948754+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5zekil6e', '--error-file', '/tmp/tmpw0tzvo72']
[2023-06-09 13:51:52,171] {standard_task_runner.py:77} INFO - Job 31: Subtask dbt-1
[2023-06-09 13:51:52,210] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.dbt-1 manual__2023-06-09T13:51:50.948754+00:00 [running]> on host d78e0722255b
[2023-06-09 13:51:52,262] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=dbt-1
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T13:51:50.948754+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-09T13:51:50.948754+00:00
[2023-06-09 13:51:52,263] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-06-09 13:51:52,263] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'dbt run --models dbt1 --profiles-dir /opt/***/dbt/part3/ --project-dir /opt/***/dbt/part3/']
[2023-06-09 13:51:52,269] {subprocess.py:85} INFO - Output:
[2023-06-09 13:51:54,577] {subprocess.py:89} INFO - [0m13:51:54  Running with dbt=1.5.1
[2023-06-09 13:51:54,677] {subprocess.py:89} INFO - [0m13:51:54  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2023-06-09 13:51:54,677] {subprocess.py:89} INFO - There are 1 unused configuration paths:
[2023-06-09 13:51:54,677] {subprocess.py:89} INFO - - models.part3.example
[2023-06-09 13:51:54,688] {subprocess.py:89} INFO - [0m13:51:54  Found 2 models, 0 tests, 0 snapshots, 0 analyses, 307 macros, 0 operations, 0 seed files, 0 sources, 0 exposures, 0 metrics, 0 groups
[2023-06-09 13:51:54,689] {subprocess.py:89} INFO - [0m13:51:54
[2023-06-09 13:51:54,744] {subprocess.py:89} INFO - [0m13:51:54  Concurrency: 1 threads (target='dev')
[2023-06-09 13:51:54,745] {subprocess.py:89} INFO - [0m13:51:54
[2023-06-09 13:51:54,750] {subprocess.py:89} INFO - [0m13:51:54  1 of 1 START sql table model public.dbt1 ....................................... [RUN]
[2023-06-09 13:51:54,883] {subprocess.py:89} INFO - [0m13:51:54  1 of 1 OK created sql table model public.dbt1 .................................. [[32mSELECT 13[0m in 0.13s]
[2023-06-09 13:51:54,962] {subprocess.py:89} INFO - [0m13:51:54
[2023-06-09 13:51:54,963] {subprocess.py:89} INFO - [0m13:51:54  Finished running 1 table model in 0 hours 0 minutes and 0.27 seconds (0.27s).
[2023-06-09 13:51:54,969] {subprocess.py:89} INFO - [0m13:51:54
[2023-06-09 13:51:54,969] {subprocess.py:89} INFO - [0m13:51:54  [32mCompleted successfully[0m
[2023-06-09 13:51:54,970] {subprocess.py:89} INFO - [0m13:51:54
[2023-06-09 13:51:54,970] {subprocess.py:89} INFO - [0m13:51:54  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2023-06-09 13:51:57,029] {subprocess.py:93} INFO - Command exited with return code 0
[2023-06-09 13:51:57,048] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=dbt-1, execution_date=20230609T135150, start_date=20230609T135152, end_date=20230609T135157
[2023-06-09 13:51:57,077] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-06-09 13:51:57,102] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
